### ISSUE TITLE
Amadeus API Integration: Implement Flight Search and Hotel Search API Integration

### ISSUE THREAD

**Issue by rajavishah** [Sheetalpujarii/CSYE7230-TravelWing#27]

**Comment by SanathLNU** [comment]
As a Developer, I would like to integrate the Amadeus Flight and Hotel Search API so that users can search for flights and hotels based on their requirements directly from our application.

### Detailed Description
We need to integrate the Amadeus Flight Offers Search API into our existing MERN and Next.js application to provide our users with the ability to search for flights and hotels. The integration should allow users to:

1.  input their search criteria, such as origin, destination, departure date, and number of adults, to search for the flights and retrieve a list of available flights
2.  input their destination to search for hotels and retrieve a list of available hotels and retrieve a list of available hotels. 

This feature will enhance our application's functionality by offering comprehensive travel planning services, including both accommodation and flight options

### Acceptance Criteria

- [ ] The backend should successfully integrate with the Amadeus Flight Search API.
- [ ] The backend should successfully integrate with the Amadeus Hotel Search API.
- [ ] The application must securely manage the API access token, retrieving it as needed without exposing sensitive credentials.
- [ ] Proper basic error handling should be in place to manage and respond to API errors.
